### ISSUE TITLE
Custom Hostnames feature within SSL for SaaS solution

### ISSUE THREAD

**Issue by sc0ttbeardsley** [paultyng/terraform-provider-cloudflare#336]
We (Pinterest) would like to use terraform to support the custom hostnames feature within SSL for SaaS on Cloudflare. This would allow use to store TLS configurations (eg H2 is enabled/disabled) while still bringing our own custom certs.

### Terraform Version
Terraform v0.11.13
+ provider.cloudflare v1.13.0

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_*

This is a feature request for an unsupported resource type.

**Comment by jacobbednarz** [comment]
We also use SSL for SaaS but for third party sites we host via the API and not with lifecycle management that Terraform does. Regarding your use case, will it be for domains you control internally? 

I’ll take a look at the documentation we have for it and see what resources I can form from it and whether there are any known caveats to it before getting too far down with implementing this.

**Comment by JoeAshworth** [comment]
+ 1 for wanting this. (Booking.com)

We're currently interacting with the API to do this, but a Terraform resource for this would be extremely useful.

**Comment by masonbivens** [comment]
It looks like someone has implemented this via a custom provider. Not sure what it would take to actually get this implemented in the official provider though.

https://github.com/oh4real/terraform-provider-flare/commit/b2f2e2267a5f34f69bec015f065ce623d1fa47aa

**Comment by marco-fp** [comment]
Any update on this issue? We (Education First) would also benefit from this feature.

**Comment by tguvdamm** [comment]
We (DoubleVerify) would also benefit from this feature. I thumbs-upped the original post for visibility.

**Comment by jacobbednarz** [comment]
#746 adds support for this as a new resource. Please check it out, pull it locally, build the provider and let me know in that PR if you hit any snags.
